linters:
  enable:
    - gofmt
    - govet
    - revive
    - gosec
    - misspell
    - exportloopref
    - dupl
    - gosimple
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/rancher/distros-test-framework

  revive:
    confidence: 0.8
    severity: warning
    ignore-generated-header: true
    rules:
      - name: line-length-limit
        arguments: [120]
      - name: cognitive-complexity
        arguments: [10]
      - name: bare-return
      - name: blank-imports
      - name: confusing-results
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: get-return
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: import-shadowing
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: range
      - name: range-val-in-closure
      - name: receiver-naming
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
        arguments: ["fmt.Printf", "builder.WriteString"]
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver

issues:
  exclude-rules:
    - linters: [typecheck]
      text: "command-line-arguments"
    - linters: [gosec]
      text: "G106: Use of ssh InsecureIgnoreHostKey should be audited"
    - linters: [gosec]
      text: "G306: Expect WriteFile permissions to be 0600 or less"
    - linters: [revive]
      text: 'Unhandled error in call to function fmt\.Println'
    - linters: [govet]
      text: '`fmt\.Println` arg list ends with redundant newline'
