linters:
  enable:
    - gofmt
    - govet
    - revive
    - gosec
    - misspell
    - dupl
    - gosimple
    - staticcheck
    - nlreturn
    - funlen
    - gocritic
    - godot
    - perfsprint
    - usestdlibvars
    - whitespace

linters-settings:
  funlen:
    lines: 55
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
  misspell:
    locale: "US"
  gofmt:
    simplify: true
  gci:
    sections:
      - standard
      - default
      - prefix("github.com/rancher/distros-test-framework")
  nlreturn:
    block-size: 4
  revive:
    confidence: 0.8
    severity: error
    ignore-generated-header: true
    rules:
      - name: line-length-limit
        arguments: [125]
      - name: bare-return
      - name: blank-imports
      - name: confusing-results
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: errorf
      - name: exported
      - name: get-return
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: import-shadowing
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: range
      - name: range-val-in-closure
      - name: receiver-naming
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unhandled-error
        arguments: ["fmt.Printf", "builder.WriteString"]
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver

issues:
  exclude-files:
    - "pkg/testcase/selinux.go"
    - ".*_suite_test.go"
    - "pkg/testcase/unit/rke2windowsutils_test.go"
  exclude-rules:
    - linters: [typecheck]
      text: "command-line-arguments"
    - linters: [gosec]
      text: "G106: Use of ssh InsecureIgnoreHostKey should be audited"
    - linters: [gosec]
      text: "G306: Expect WriteFile permissions to be 0600 or less"
    - linters: [revive]
      text: 'Unhandled error in call to function fmt\.Println'
    - linters: [govet]
      text: '`fmt\.Println` arg list ends with redundant newline'
    - linters: [nlreturn]
      text: 'continue with no blank line before'
    - linters: [revive]
      text: 'should not use dot imports '
